### ISSUE TITLE
Launch MDL in any region

### ISSUE THREAD

**Issue by nateiam** [FINRAOS/herd-mdl#64]
Observed in MDL:
Herd fails to launch EMR clusters in regions other than the default (us-east-1)

Steps to reproduce
Install MDL in us-west-2 (or any other region)

Defective Behavior

Metastor (nested) stack fails to create because cluster creation fails. The underlying issue is that while trying to launch an EMR cluster to process Herd objects it looks for subnets in the us-east-1 region which are not available.

Desired Behavior

EMR cluster-create 'action' looks for subnets in the region where the stack is deployed.

**Comment by kusid** [comment]
Observed in MDL:
Herd fails to launch EMR clusters in regions other than the default (us-east-1)

Steps to reproduce
Install MDL in us-west-2 (or any other region)

Defective Behavior

Metastor (nested) stack fails to create because cluster creation fails. The underlying issue is that while trying to launch an EMR cluster to process Herd objects it looks for subnets in the us-east-1 region which are not available. 

Desired Behavior

EMR cluster-create 'action' looks for subnets in the region where the stack is deployed.

**Comment by kusid** [comment]
Dev comments:
With the proper fix available in Herd - we will upgrade the appropriate Herd version reference in the MDL CFT and attempt to install a new stack in us-west-2.
