### ISSUE TITLE
Herd stack creation failure - Error 500 during "enableSSLAndAuth" installation

### ISSUE THREAD

**Issue by bkbwese** [FINRAOS/herd-mdl#89]
## Description
CloudFormation installation does not complete when enabling 'EnableSSLAndAuth'. Error 500 occurs during `configureAndStartHerd.sh` in the 'enableSSLAndAuth' section (line 182~189). The logs error output indicate `Please update "herd.notification.user.namespace.authorization.change.message.definitions" configuration entry` which contradicts what is specified in the code configuration (ConfigurationValue.java) for that field "There is no default value which will cause no messages to be sent."

## Steps to reproduce
1. Upload installMDL.yaml to CloudFormation
2. Modify parameters with the following (I've modified my domain/ssl parameters with generic ones:
    * DeployComponents = Herd
    * CertificateInfo = certificate info (ex: "CN=*.mydomain.com")
    * HerdDBClass = db.m5.large (without this being modified herd fails at RDS DB creation)
    * CreateOpenLDAP = true
    * CertificateArn = certificate arn (ex: arn:aws:acm:us-east-1:1234567890:certificate/mycertificate)
    * HostedZoneName = ex: mydomain.com.
    * DomainNameSuffix = ex: mydomain.com
    * EnableSSLAndAuth = true
4. CloudFormation stack will fail, logs are in CloudWatch

## Relevant logs

CloudFormation output - HerdEC2Stack

| Timestamp                    | Logical ID                                             | Status        | Status Reason                                                    |
| ---                          | ---                                                    | ---           | ---                                                              |
| 2019-07-29 10:13:19 UTC-0600 | eval-MdlStack-1T46P4XH491ZZ-HerdEC2Stack-19E38V7YEU6OA | CREATE_FAILED | The following resource(s) failed to create: [HerdWaitCondition]. |
| 2019-07-29 10:13:18 UTC-0600 | HerdWaitCondition                                      | CREATE_FAILED | WaitCondition timed out. Received 0 conditions when expecting 1  |

Herd codedeploy
```
[2019-07-29 16:05:20.869] [d-19OME41WN][stdout]07/29/2019 16:05:20 *** ERROR *** curl --request POST --header 'Content-Type: application/json' --data '
{
    "userNamespaceAuthorizationKey": {
        "userId": "mdl_user",
        "namespace": "MDL"
    },
    "namespacePermissions": [
        "READ",
        "WRITE"
    ]
}
' https://AWSALBevalHerdeval-1761683017.us-east-1.elb.amazonaws.com/herd-app/rest/userNamespaceAuthorizations --insecure has failed with error 500
```

Herd application logs
```
Jul-29-2019 16:05:20.805 [ajp-nio-8009-exec-2] DEBUG org.finra.herd.ui.RequestLoggingFilter.logRequest userId=admin_user - HTTP Request [uri=/herd-app/rest/userNamespaceAuthorizations;method=POST;client=10.0.10.189;session=E1E4FB1B9FEEF0BCE3E0A27064AEE840;payload=
{
    "userNamespaceAuthorizationKey": {
        "userId": "mdl_user",
        "namespace": "MDL"
    },
    "namespacePermissions": [
        "READ",
        "WRITE"
    ]
}
]
Jul-29-2019 16:05:20.843 [ajp-nio-8009-exec-2] ERROR finra.herd.service.helper.HerdErrorInformationExceptionHandler.logError userId=admin_user - A general error occurred.
java.lang.IllegalStateException: Notification message destination must be specified. Please update "herd.notification.user.namespace.authorization.change.message.definitions" configuration entry.
at org.finra.herd.service.helper.notification.AbstractNotificationMessageBuilder.buildNotificationMessages(AbstractNotificationMessageBuilder.java:146) ~[herd-service-0.81.0.jar:?]
at org.finra.herd.service.helper.notification.NotificationMessageManager.buildNotificationMessages(NotificationMessageManager.java:100) ~[herd-service-0.81.0.jar:?]
at org.finra.herd.service.impl.MessageNotificationEventServiceImpl.processUserNamespaceAuthorizationChangeNotificationEvent(MessageNotificationEventServiceImpl.java:98) ~[herd-service-0.81.0.jar:?]
at org.finra.herd.service.impl.MessageNotificationEventServiceImpl$$FastClassBySpringCGLIB$$bb1fb8f9.invoke(<generated>) ~[herd-service-0.81.0.jar:?]
a
```

**Comment by btgrant-76** [comment]
I'm also having some issues using the EnableSSLAndAuth option. @bkbwese did you happen to get this sorted out? In the docs, the "turnkey" instructions reference a YML files with version 1.4.0 while the "advanced install" options reference a YML file with version 1.1.0. I tried 1.1.0 most recently and I think I'll give 1.4.0 a try tomorrow & see if I have any better luck.

**Comment by bkbwese** [comment]
@btgrant-76 I was not able to get this figured out. Was hoping I would get a response here, but nothing so far. My project is delayed for internal reasons, so I have not done any more digging.

**Comment by kusid** [comment]
Hello @bkbwese and @btgrant-76 ! I would like to apologize for not looking into this earlier.

Basically, the underlying issue is this inline lambda function [here](https://github.com/FINRAOS/herd-mdl/blob/master/mdl/src/main/cft/mdlCreateNsAuthSyncUtil.yml#L130-L183) which was originally configured to run on nodejs4.3 platform which used to work just fine but is [no longer supported](https://aws.amazon.com/blogs/developer/node-js-6-is-approaching-end-of-life-upgrade-your-aws-lambda-functions-to-the-node-js-10-lts/). Simply dropping in nodejs10.x does not help either because it [does not support cfn-module](https://forums.aws.amazon.com/thread.jspa?messageID=920416). There's a workaround which involves simply wrapping the callback in a promise but I would like to provide an elegant fix and not a hacky solution. I'm actively looking into this and will send out an update tomorrow. Thank you.

**Comment by bkbwese** [comment]
Hey @kusid! Thanks for picking this up. I noticed the deprecated version of Node that was being used, but I don't think that Lambda function is used in a herd-only component deployment. I think that might be a different issue than what I described initially. The lambda you reference [here](https://github.com/FINRAOS/herd-mdl/blob/master/mdl/src/main/cft/mdlCreateNsAuthSyncUtil.yml#L130-L183), uses a condition ["DeployBDSQLWithAuth"](https://github.com/FINRAOS/herd-mdl/blob/master/mdl/src/main/cft/mdl.yml#L174) which only executes with BDSQL or All components (I think?).

Perhaps a different issue needs to be created for the deprecated version of node.

**Comment by kusid** [comment]
Hi @bkbwese You are absolutely right! Actually we need our [namespace-auth](https://finraos.github.io/herd-mdl/docs/authorizations-overview/#herd-a-unified-access-control-provider) sync lambda to only deploy alongside the BDSQL (managed presto) component. 
Some background: The offending lambda in question is a workaround to deal with [the issue](https://forums.aws.amazon.com/message.jspa?messageID=734756) when VPC lambdas are stalled from tearing down because AWS spins up ENIs so that lambdas can communicate from AWS' lambda VPC to a client's VPC. They have started rolling out a solution as detailed [here](https://aws.amazon.com/blogs/compute/announcing-improved-vpc-networking-for-aws-lambda-functions/) but it's not available in us-east-1 yet (which is where we normally deploy to). I'm working on a fix and we will publish a release pretty soon. Thank you.

**Comment by kusid** [comment]
Hi @bkbwese, @btgrant-76 We've pushed out a [new release](https://github.com/FINRAOS/herd-mdl/releases/tag/mdl-v1.5.0) which fixes this issue, please try it out. I've updated our documentation also.
